name: spleb
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  firebase_core: ^2.7.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  # flutter pub run flutter_launcher_icons:main && flutter pub run flutter_native_splash:create
  android: true
  ios: true
  image_path: "assets/images/ic_launcher_logo.png"
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
