name: spleb
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.14
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.15
  path_provider: ^2.0.13
  provider: ^6.0.5

dev_dependencies:
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  # flutter pub run flutter_launcher_icons:main && flutter pub run flutter_native_splash:create
  android: true
  ios: true
  image_path: "assets/images/ic_launcher_spleb.png"
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true

flutter_native_splash:
  image: assets/images/ic_launcher.png

  background_image: "assets/images/background_image.png"
  android: true
  android_12:
    image: assets/images/ic_launcher_spleb.png
    icon_background_color: "#ffffff"
  ios: true
  web: false
  ios_content_mode: center
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
