name: spleb
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  cloud_firestore: ^4.4.3
  figma_squircle: ^0.5.3
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.14
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.1.15
  font_awesome_flutter: ^10.4.0
  intl: ^0.17.0
  native_pdf_view: ^6.0.0+1
  path_provider: ^2.0.13
  provider: ^6.0.5
  search_page: ^2.3.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  # flutter pub run flutter_launcher_icons:main && flutter pub run flutter_native_splash:create
  android: true
  ios: true
  image_path: "assets/images/ic_launcher_spleb.png"
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true

flutter_native_splash:
  image: assets/images/ic_launcher.png

  background_image: "assets/images/background_image.png"
  android: true
  android_12:
    image: assets/images/ic_launcher_spleb.png
    icon_background_color: "#ffffff"
  ios: true
  web: false
  ios_content_mode: center
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/pdf/
  fonts:
    - family: "Inter"
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
